services:
  kubek:
    image: ghcr.io/ericktucto/kubek:latest
    restart: unless-stopped
    ports:
      - "${PORT_DASHBOARD:-3000}:3000"
      - "${PORT_MINECRAFT:-25565}:25565"
    volumes:
      - ./servers:/app/servers
      - ./logs:/app/logs
      - ./binaries:/app/binaries
